<?php
// $Id$

/**
 * @file
 * Manages liveandtell images.
 *
 * When enabled, the Drupal lnt_images module allows a user
 * to add terms to a liveandtell image.
 */
 
/**
 * Implementation of hook_init().
 */
function lnt_images_init() {
  //variable_set("font-lakota", "Lakhota Gmigmeya");
  //variable_set("font-english", "Arial");
}
 
/**
 * Implementation of hook_perm().
 */
function lnt_images_perm() {
    return array('advanced edit lnt_image');
}





/**
 * Implementation of hook_nodeapi().
 */
function lnt_images_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  
  if ($node->type == 'lnt_image') {
    
    switch ($op) {
      
      case 'presave':
        
        //
        // ON SUBMIT LIVE-AND-TELL IMAGE
        //
        
        // Apply string replacement to XML field
        $xml_data = $node->field_lnt_image_xml[0]['value'];
        if (is_null($xml_data)) {
          // THIS DEFAULT VALUE IS ONLY A PRECAUTION FOR LEGACY NODES
          // THE DEFAULT XML WILL COME FROM CCK FIELD'S DEFAULT VALUE
          $xml_data = '<controls><image url="@URL" text="@TITLE" /></controls>'; 
        } 
        $xml_imgpath = 'http://' . $GLOBALS['_SERVER']['HTTP_HOST'] . base_path() . file_directory_path(). '/imagecache/lnt_image_fullsize/lnt_image/' . $node->field_lnt_image[0]['filename'];
        $xml_data = str_replace('@TITLE', $node->title, $xml_data);
        $xml_data = str_replace('@URL', $xml_imgpath, $xml_data);
        $node->field_lnt_image_xml[0]['value'] = $xml_data;
        break;
        
      case 'update':
        
        //
        // ON UPDATE LIVE-AND-TELL IMAGE
        //
      
        lnt_image_update_terms($node);
        break;
        
      case 'view':
        
        //
        // ON VIEW LIVE-AND-TELL IMAGE
        //
      
        $teaser = $a3;
        $page = $a4;
        if ($page) {
          // Set breadcrumb
          $album_node = node_load($node->field_lnt_album_noderef[0]['nid']);
          $language_term = array_shift(taxonomy_node_get_terms_by_vocabulary($album_node, 1));
          $language_term_lower = drupal_strtolower($term->name);
          $breadcrumb[] = l('Home', NULL);
          $breadcrumb[] = l('Picture book', 'picture-book');
          $breadcrumb[] = l($language_term->name, "picture-book/$language_term_lower");
          $breadcrumb[] = l($album_node->title, "node/$album_node->nid");
          $breadcrumb[] = l($node->title, $_REQUEST['q']);
          drupal_set_breadcrumb($breadcrumb);
        }
        break;
        
    } // end switch
  } // end if
  
}


/**
 * Implementation of hook_menu().
 */
function lnt_images_menu() {
  
  // ADD TERMS TAB
  $items['node/%node/add-terms'] = array(
    'title' => 'Tag picture',
    'page callback' => 'lnt_image_editor',
    'page arguments' => array(1),
    'access callback' => 'lnt_node_access_and_type',
    'access arguments' => array('update', 1, 'lnt_image'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0
  );

  // ORDER TERMS TAB
  $items['node/%node/sort-terms'] = array(
    'title' => 'Sort terms',
    'page callback' => 'lnt_order_terms_page',
    'page arguments' => array(1),
    'access callback' => 'lnt_node_access_and_type',
    'access arguments' => array('update', 1, 'lnt_image'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0
  );

  // OPEN FILE
  $items['openfile'] = array(
    'title' => 'Open file',
    'page callback' => 'lnt_openfile',
    'access callback' => TRUE, // <-- NEED TO FIGURE THIS OUT!!
    //'access callback' => 'node_access',
    //'access arguments' => array('view', 'lnt_image'),
    'type' => MENU_CALLBACK
  );

  // SAVE FILE
  $items['savefile'] = array(
    'title' => 'Save file',
    'page callback' => 'lnt_savefile',
    'access callback' => TRUE, // <-- NEED TO FIGURE THIS OUT!!
    //'access callback' => 'node_access',
    //'access arguments' => array('update', 'lnt_image'),
    'type' => MENU_CALLBACK
  );

  return $items;

}

/**
 * Implementation of hook_menu_alter().
 */
function lnt_images_menu_alter(&$items) {

  /*
  // ADD TERMS TAB
  $items['node/%node/edit'] = array(
    'title' => 'Categorize',
    'page callback' => 'node_page_edit',
    'page arguments' => array(1),
    'access callback' => 'lnt_node_access_and_type',
    'access arguments' => array('update', 1, 'lnt_image'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0
  );
  */

}


/**
 * Implementation of hook_theme().
 */
function lnt_images_theme($existing, $type, $theme, $path) {
  return array(
    'lnt_order_terms_form' => array(
      'arguments' => array('form' => NULL),
    ),
    'lat_image_viewer_embed_code' => array(
      'arguments' => array('node' => NULL, 'width' => NULL, 'height' => NULL, 'query_string' => NULL),
      'template' => 'latimage-viewer-embed-code',
      'path' => "$path/theme",
      'file' => 'theme.inc',
    ),
    'lat_image_editor_embed_code' => array(
      'arguments' => array('node' => NULL, 'width' => NULL, 'height' => NULL, 'query_string' => NULL),
      'template' => 'latimage-editor-embed-code',
      'path' => "$path/theme",
      'file' => 'theme.inc',
    )
  );
}

/**
 * Imeplementation of hook_preprocess_page
 *
 * Prepend the $head_title theme variable with "term" and "example" text
 * This is more useful information when sharing Web pages on Facebook.
 */
function lnt_images_preprocess_page(&$vars) {

  // Verify page node
  if (!array_key_exists('node', $vars)) {
    return;
  }

  // Initialize node variable
  $node = $vars['node'];  
  
  // Verify 'lnt_image' node
  if ($node->type == 'lnt_image') {

    // Initialize title text variable  
    $title_text = '';
  
    //
    //Retrieve term text
    //
    
    $query_to_retrieve_terms = <<<EOQ
      SELECT 
        node.title AS node_title
      FROM 
        {node} node
          LEFT JOIN 
        {content_type_lnt_term} term
          ON node.vid = term.vid
      WHERE 
        (node.type in ('lnt_term')) 
          AND 
        (term.field_lnt_image_noderef_nid = %d)
EOQ;
    $record_set = db_query($query_to_retrieve_terms, $node->nid);
    while ($row = db_fetch_object($record_set)) {
      $row_text = trim($row->node_title);
      if ($row_text != '') {
        $title_text .=  "$row_text; ";
      }
    } // while
    
    //
    // Retrieve example sentence text
    //
    
    $query_to_retrieve_examples = <<<EOQ
      SELECT 
        example.field_lnt_image_text_examples_text
      FROM 
        {node} node 
          LEFT JOIN 
        {content_field_lnt_image_text_examples} example 
          ON node.vid = example.vid
      WHERE 
        (node.type in ('lnt_image')) AND (node.nid = %d)
EOQ;
    $record_set = db_query($query_to_retrieve_examples, $node->nid);
    while ($row = db_fetch_object($record_set)) {
      $row_text = trim($row->field_lnt_image_text_examples_text);
      if ($row_text != '') {
        $title_text .=  "$row_text; ";
      }
    } // while    

    //Trim title text    
    $title_text = trim($title_text);

    //
    // Now set the page title
    //
    
    $page_title = $vars['head_title'];
    $page_title_length = strlen($page_title);
    $cutoff_length = 64 - $page_title_length - 5;
    if ($title_text > $cutoff_length) {
      $title_text = substr($title_text, 0, $cutoff_length);
    }
    $vars['head_title'] = $title_text. ' ... ' . $page_title;
    
  } // if
  
} // function


/**
 * Implementation of hook_form_alter.
 */
function lnt_images_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'lnt_image_node_form') {
  
    //drupal_set_message('<pre>'.print_r($form,true).'</pre>');
    $user = $GLOBALS['user'];

    //
    // CREATING or EDITING a node
    //
    //   Preconditions:
    //     User missing "advanced edit lnt_image" permission
    //
    //   Action:
    //     Convert XML textarea to a hidden value
    //

    if (user_access('advanced edit lnt_image', $user) == false) {
      $form['field_lnt_image_xml'][0]['#type'] = 'value';
      $form['field_weight'][0]['#type'] = 'value';
    }

    //
    // EDITING an existing node
    //
    //   Preconditions:
    //     User missing "advanced edit lnt_image" permission
    //     Node was already created, i.e. $form['nid']['#value']
    //
    //   Action:
    //     Remove image "upload" button
    //

    if (user_access('advanced edit lnt_image', $user) == false) {
      if (isset($form['nid']['#value'])) {
        $form['field_lnt_image'][0]['#post_render'] = array('lnt_post_render_lnt_image_node_form');
      }
    }

    //
    // CREATING or EDITING a node for a particular album
    //
    //   Preconditions:
    //     Album is an additional argument, e.g. /node/add/lnt_image/123
    //
    //   Action:
    //     Set default album to the additional argument
    //     i.e. $form['field_lnt_album_noderef']['#default_value'][0]['nid']
    //

    //drupal_set_message(arg(3));
    $album_ref = arg(3);
    if (is_numeric($album_ref)) {
      $form['field_lnt_album_noderef']['#type'] = 'value';
      $form['field_lnt_album_noderef']['#default_value'][0]['nid'] = $album_ref;
    }

  }
}





/**
 * Accepts a form and a node object.
 *
 * @param $form
 *  A form object.
 *
 * @param $node
 *  A node object.
 *
 * @return
 *   A themed ordered list of terms.
 */
function theme_lnt_order_terms_form($form, $node = null) {

  drupal_add_tabledrag('term-table', 'order', 'sibling', 'weight');

  foreach ($form['rows'] as $field_id => $field) {
    if (intval($field_id)) {        //make sure FIELD-ID => NID
      $row = $field['data']['#value'];
      $row[] = drupal_render($form['rows'][$field_id][$field_id]);
      //drupal_set_message('<pre>'.print_r($row,true).'</pre>');
      $rows[] = array('data' => $row, 'class' => 'draggable');
    }
  }

  $header = array('Terms/Phrases', 'Weight');
  $output = theme_table($header, $rows, array('id' => 'term-table'));
  $output .= drupal_render($form);
  return $output;

}

/**
 * Accepts a form state and a node.
 *
 * @param $form_state
 *  The state of the form.
 *
 * @param $node
 *  A node object.
 *
 * @return
 *  A form for ordering terms is returned.
 */
function lnt_order_terms_form(&$form_state, $node = null) {

  //drupal_set_message('<pre>'.print_r($node,true).'</pre>');

  // TERM.NID, TERM.TITLE, TERM.WEIGHT
  $rset = db_query(
    "select n.nid, n.title, w.field_weight_value as weight "
    ."from {node} n, {content_type_lnt_term} t, {content_field_weight} w "
    ."where n.nid = w.nid and n.nid = t.nid and n.type = 'lnt_term' "
    ." and t.field_lnt_image_noderef_nid = %d "
    ."order by weight, n.title ",
    $node->nid
  );

  while($row = db_fetch_object($rset)) {

    $row_weight = is_null($row->weight) ? 0 : $row->weight;

    $form['rows'][$row->nid]['data'] = array(
      '#type' => 'value',
      '#value' => array($row->title)
    );

    $form['rows'][$row->nid][$row->nid] = array(
      '#type' => 'textfield',
      '#size' => 5,
      '#default_value' => $row_weight,
      '#attributes' => array('class' => 'weight')
    );
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit'
  );

  return $form;

}

/**
 * The submit handler for the lnt_order_terms_form form.
 */
function lnt_order_terms_form_submit(&$form, &$form_state) {
  //lnt_verbose($form_state, true);
  foreach($form_state['values'] as $nid => $weight) {
    if (intval($nid)) {
      //lnt_verbose("$nid $weight");
      $rset = db_query(
        "update {content_field_weight} w "
        ."set w.field_weight_value = %d "
        ."where w.nid = %d ",
        $weight, $nid
      );
    }
  }
}





/**
 * Accepts an operation, a node, and a type.
 *
 * @param $op
 *  A node operation.
 *
 * @param $node
 *  A reference to a node
 *
 * @param $type
 *  A node type
 *
 * @return
 *  TRUE is returned if the type property of $node matches the $type
 *  parameter and the user has permission to perform the operation
 *  in $op on $node.  Otherwise FALSE is returned.
 */
function lnt_node_access_and_type($op, &$node, $type) {
  return $node->type == $type && node_access($op, $node);
}



/**
 * Accepts a filepath and an imagecache preset.
 *
 * @param $filepath
 *  The path to the image.
 *
 * @param $preset
 *  An imagecache preset
 *
 * @return
 *   An array with the image width and height.
 */
function get_lnt_image_dimensions($filepath, $preset = 'lnt_image_fullsize') {
  $base_path = $GLOBALS['base_path']; 
  $filepath = str_replace('dev.liveandtell.com', 'liveandtell.com', $filepath);
  //$img  = $GLOBALS['_SERVER']['DOCUMENT_ROOT'].'/drupal6/'.$base_path.$filepath;
  $img  = $GLOBALS['_SERVER']['DOCUMENT_ROOT'].'/'.$base_path.$filepath;
  $preset = imagecache_preset_by_name($preset);
  $action = $preset['actions'][0];
  $imgdata = imageapi_image_open($img);
  _imagecache_apply_action($action, $imgdata);
  return array(
  'width' => $imgdata->info['width'], 
  'height' => $imgdata->info['height']
  );
}




/**
 * Accepts the contents of a node.
 *
 * @param $content
 *  The contents of a node object.
 *
 * @return
 *  Returns the content with the additional submit function removed.
 */
function lnt_post_render_lnt_image_node_form($content) {
    $content = preg_replace('/<input type="submit".*?\/>/','',$content);
    return $content;
}

/**
 * Accepts a file path.
 *
 * @param $file_path
 *  A file path.
 *
 * @return
 *  Return a stripped filename.
 */
function lnt_strip_image_path($file_path) {
  $file_path = str_replace('dev.liveandtell.com', 'liveandtell.com', $file_path);
  $filename = str_replace(file_directory_path().'/lnt_image/', '', $file_path);
  return $filename;
}



/**
 * Accepts a filename, a node type, and an imagecache preset
 *
 * @param $filename
 *  The image filename.
 *
 * @param $node_type
 *  The type of node.
 *
 * @param $imagecache_preset
 *  An imagecache preset.
 *
 * @return
 *  A url to the image is returned.
 */
function lnt_get_image_url($filename, $width, $height, $node_type) {
  if ($width || $height) {
    // Dynamically created preset
    $preset = "/dynamicscale/$width/$height/";
  }
  else {
    $preset = "/imagecache/lnt_image_fullsize/";
  }

  return 'http://' . $GLOBALS['_SERVER']['HTTP_HOST'] . 
                     base_path() .
                     file_directory_path() .
                     $preset .
                     $node_type . '/' .
                     $filename;
}




/**
 * Accepts a node reference.
 *
 * @param $node
 *  A node object.
 *
 * @return
 *  The HTML code for the image editor is returned.
 */
function lnt_image_editor(&$node) {
  // GET IMAGE DIMENSIONS
  $result = db_query('select f.filepath from {content_type_lnt_image} c, {files} f where c.field_lnt_image_fid = f.fid and c.nid = %d', $node->nid);
  $filepath = db_fetch_object($result)->filepath;
  $img_dim = get_lnt_image_dimensions($filepath);
  $img_dim['width'] = 955; //$img_dim['height'] = 540;
  $img_dim['height'] = $img_dim['height'] + 200; //$img_dim['height'] = $img_dim['height'] + 100; //original height adjustment  
  $language = reset(taxonomy_node_get_terms_by_vocabulary($node, 1));
  $languageName = drupal_strtolower($language->name);
  //$fontFamily = variable_get("font-$languageName", "Gentium, DejaVu");
  if ($languageName == 'lakota') {
    $fontFamily = 'Lakhota Gmigmeya'; }
  else if ($languageName == 'english') {
    $fontFamily = 'Arial'; }
  else {
    $fontFamily = 'Gentium, DejaVu'; }  
  $embed_code = theme('lat_image_editor_embed_code', $node, $img_dim['width'], $img_dim['height'], null);
  return $embed_code;
}

/**
 * Acceps a node object.
 *
 * @param $node
 *  A node object.
 *
 * @return
 *  The lnt_order_terms_form form is returned.
 */
function lnt_order_terms_page($node) { 
  return drupal_get_form('lnt_order_terms_form', $node); 
}

/**
 * Accepts data to print and a boolean to determine if we
 * are using print_r
 *
 * @param $data
 *  The data to print.
 *
 * @param $use_print_r
 *  TRUE if using print_r to print data.
 */
function lnt_verbose($data, $use_print_r = false) {

  if ($GLOBALS['user']->uid != 1) 
    return;

  if ($use_print_r == false) {
    drupal_set_message('<pre>'.htmlentities($data).'</pre>');
  } else {
    drupal_set_message('<pre>'.htmlentities(print_r($data,true)).'</pre>');
  }

}



/**
 * Returns a lnt_image node.
 *
 * @return
 *  A lnt_image node is returned.
 */
function lnt_openfile() {

  drupal_set_header('Content-Type: text/plain');
  $nid = $_REQUEST['nid'];
  $node = node_load($nid);  
  $width = $_REQUEST['width'];
  $height = $_REQUEST['height'];
  
  //
  // POST-PROCESS XML
  //
  
  $xmldata = $node->field_lnt_image_xml[0]['value'];
  //$xmldata = str_replace('dev.liveandtell.com', 'liveandtell.com', $xmldata);

  //
  // Set actual image name
  //

  // MAY NOT BE COMPATIBLE WITH FUTURE MODIFICATIONS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  $img_filepath = $node->field_lnt_image[0]['filepath'];
  $img_filename = lnt_strip_image_path($img_filepath);
  $img_url = lnt_get_image_url($img_filename, $width, $height, $node->type);
  $xmldata = preg_replace('/image url=".*?"/', 'image url="'.$img_url.'"', $xmldata);
  //lnt_verbose($img_url);
  //lnt_verbose($node, true);
  //lnt_verbose(base_path());
  //lnt_verbose(file_directory_path());
  
  //
  // Replace term text with text from actual term
  //
  
  // PREPARE XML DOCUMENT AND XPATH
  $xmldoc = new DOMDocument('1.0', 'UTF-8');
  $success = $xmldoc->loadXML($xmldata);
  if ($success) {
    $xpath = new DOMXPath($xmldoc);
    $button_elements = $xpath->query('//button|//circle|//rectangle|//square');
    if ($button_elements) {
      foreach($button_elements as $button) {
        
        //
        // Find the Term ID
        //
        
        $term_nid = $button->getAttribute('termNID');
        if (!$term_nid) {
          // Figure out the Term NID.
          $button_id = $button->getAttribute('id');
          if ($button_id) {
            $term_nid = db_result(db_query( <<<EOS
              select 
                n.nid 
              from 
                {node} n inner join 
                {content_type_lnt_term} c on n.nid = c.nid
              where
                c.field_lnt_image_noderef_nid = $node->nid
                and c.field_lnt_image_element_id_value = $button_id
EOS
            ));
          }
          else {
            drupal_set_message('Button ID not foundin XML element.', 'warning');
          }
        }
        else {
          // Continue as normal. Term NID was found.
        }
        
        //
        // Load the term
        //
        
        if ($term_nid) {
          $term_node = node_load($term_nid);
          if ($term_node) {
            $button->setAttribute('text', $term_node->field_entry_text[0]['value']);
          }
          else {
            drupal_set_message('Failed to load node.', 'warning');
          }
        }
        else {
          drupal_set_message('Term ID missing for button element..', 'warning');
        }
        
      } // end foreach
      
      $xmldata = $xmldoc->saveXML();
      
    }
    else {
      // XPATH returned no results.
    }
  }
  else {
    // Problems loading XML document.
  }

  //
  // Get font-family
  //

  $rset = db_query(
    "select pv.value "
    ."from {profile_fields} pf, {profile_values} pv "
    ."where pf.fid = pv.fid and pf.name = 'profile_font_family' and pv.uid = %d ",
    $node->uid
  );
  $font_family = db_result($rset);
  // 1. REMOVE any existing "fontFamily" attributes
  // 2. INSERT new "fontFamily" attributes
  $xmldata = preg_replace('/fontFamily=".*?"/', '', $xmldata);
  $xmldata = str_replace('<button ', '<button fontFamily="'.$font_family.'" ', $xmldata);

  // How did this end up trimmed to just 'echo $xmldata'?
  // The server needs to send a 'success=true', just like savefile does
  echo $xmldata;

  module_invoke_all('exit');
  exit;
}



/**
 * Saves a lnt_image node.
 */

function lnt_savefile() {

  //Print header
  drupal_set_header('Content-Type: text/xml');
  echo '<?xml version="1.0" ?' . '>';

  //
  // UPDATE IMAGE NODE
  //

  //Get NODE and HTTP data
  $nodeNID = $_POST['nid'];
  $verbose .= 'NID:'.$nodeNID;
  $node = node_load($nodeNID);
  // Don't update title anymore
  //if ($_REQUEST['title']) {
  //  $node->title = urldecode($_REQUEST['title']);
  //}

  //GET NEW XML-DATA
  if ($_REQUEST['content']) {
    $xmldata = urldecode($_REQUEST['content']);
  }

  //STORE NEW XML-DATA
  $node->field_lnt_image_xml[0]['value'] = $xmldata;
  //$verbose .= $node->field_lnt_image_xml[0]['value'];

  //Save node
  //THIS PART NEEDS EXCEPTION HANDLING
  //node_validate($node);
  node_save($node);

  $verbose .= lnt_image_update_terms($node);

  //
  // RETURN RESULT
  //

  echo "\n<result success=\"true\" id=\"$node->nid\" >";
  //echo "\n<usage>\n$usage\n</usage>";
  echo "\n<verbose>\n$verbose\n</verbose>";
  echo "\n</result>";

  module_invoke_all('exit');
  exit;
}



/**
 * Accepts an lnt_image node reference and updates the terms
 *  associated with that lnt_image node.
 *
 * @param $node
 *  An lnt_image node object.
 *
 * @return
 *  The verbose output of the function for debugging purpose.
 */
function lnt_image_update_terms(&$node) {

  //
  // PREPARE TERM IDS
  //

  // PREPARE XML DOCUMENT AND XPATH
  $xmldoc = new DOMDocument('1.0', 'UTF-8');
  $success = $xmldoc->loadXML($node->field_lnt_image_xml[0]['value']);
  if (!$success) { return 'problems loading XML document'; }
  $xpath = new DOMXPath($xmldoc);

  //
  // GET XMLDATA ID's AND TEXT FOR SAVING
  //
  
  $button_list = $xpath->query('//button|//circle|//rectangle|//square');
  if (!$button_list) { 
    return 'no buttons'; 
  }
  
  $new_id_list = array();
  $new_term_list = array();
  foreach($button_list as $button) {
    $new_id_list[] = $button->getAttribute('id');
    $new_term_list[] = $button->getAttribute('text');
  }
  
  // Set empty text to "(blank)"
  foreach ($new_term_list as $term_index => $term_text) {
    if ($term_text == "") {
      $new_term_list[$term_index] = "(blank)";
    }
  }
  $verbose .= print_r($new_id_list,true);

  //
  // GET OLD TERM-IDs for a particular node
  //
  
  $query = <<<EOS
    select 
      c.nid, 
      c.field_lnt_image_element_id_value, 
      n.title
    from 
      {content_type_lnt_term} c, 
      {node} n
    where 
      c.nid = n.nid 
      and n.type = 'lnt_term'
      and c.field_lnt_image_noderef_nid = %d
    order by 
      c.field_lnt_image_element_id_value asc
EOS;
  
  $rset = db_query($query, $node->nid);
  $old_id_list = array();
  while($row = db_fetch_object($rset)) {
    $old_id_list[] = $row->field_lnt_image_element_id_value;
    $old_term_list[] = $row->title;
    $old_term_nid_list[] = $row->nid;
  }
  
  //dpm($new_id_list);   //current
  //dpm($new_term_list); //current


  //
  // UPDATE TERMS
  //
  
  // COMPARE OLD AND NEW ID'S
  // E.G. 
  // OLD: 1 2 3 5 6
  // NEW: 2 4 6 7 8 9

  // STEPS:  
  // OLD  NEW  ACTION
  // ----------------
  // 1    2    DELETE 1
  // 2    2    UPDATE 2
  // 3    4    DELETE 3
  // 5    4    INSERT 4
  // 5    6    DELETE 5
  // 6    6    UPDATE 6
  // 
  // Add 7, 8, 9  
  
  
  // Sort terms by ID, Text for comparison purposes
  if (count($new_id_list) > 1 ) {
    array_multisort($new_id_list, $new_term_list); }
  if (count($old_id_list) > 1) {
    array_multisort($old_id_list, $old_term_nid_list); }
  $verbose .= print_r($old_id_list, true);

  $old_index = 0;
  $old_count = count($old_id_list);
  $new_index = 0;
  while ($old_index < $old_count) {
  
    $old_term_nid = $old_term_nid_list[$old_index];
    $old_id = $old_id_list[$old_index];
    $new_id = $new_id_list[$new_index];
        
    // DELETE OLD TERM (THE ID'S NOT IN THE LIST OF ID'S TO BE SAVED)
    if ($old_id < $new_id) {
      //dpm('Deleting term');
      $verbose .= "\nDeleting an old term.";
      node_delete($old_term_nid);
      $old_index++;
    }
    
    // UPDATE TERM
    else if ($old_id == $new_id) {
      $verbose .= "\nUpdating an old term with the new term.";
      //dpm($old_term_nid);
      $term_node = node_load($old_term_nid);
      $term_node->title = $new_term_list[$new_index];
      $term_node->status = $node->status;                           // propogate status MAYBE HANDLE BY "RELATIONSHIPS" MODULE
      //node_validate($term_node);
      //dpm('Updating term');
      node_save($term_node);
      $old_index++;
      $new_index++;
    }
    
    // ADD NEW TERM (THE NEXT OLD ID IS GREATER THAN WHAT IS SUPPOSED TO BE ADDED, SO ADD THE NEW ONE)
    else if ($new_id < $old_id) {
      $verbose .= "\nAdding a new term.";
      $curr_term = $new_id;
      $new_term = $new_term_list[$new_index];
      $new_id = $new_id_list[$new_index];
      dpm('Adding new term');
      insert_lnt_term($GLOBALS['user'], $node, $new_term, $new_id);
      $new_index++;
    }
    
  }

  // ADD ANY REMAINING TERMS
  $new_count = count($new_id_list);
  //dpm($new_count);
  while ($new_index < $new_count) {
    $verbose .= "\nAdding a new term.";
    $new_term = $new_term_list[$new_index];
    $new_id = $new_id_list[$new_index];
    insert_lnt_term($GLOBALS['user'], $node, $new_term, $new_id);
    $new_index++;
  }

  return $verbose;
}



/**
 * Accepts a user reference, an lnt_image node reference, a title, and a term id.
 * Inserts a term into the lnt_image node.
 *
 * @param $user
 *  A reference to the user.
 *
 * @param $lnt_image_node
 *  A reference to the lnt_image node.
 *
 * @param $title
 *  The node title.
 *
 * @param $term_id
 *  The term id to instert.
 */
function insert_lnt_term(&$account, &$lnt_image_node, $title, $term_id) {

    // PREPARE NODES
    $term = array();
    $term['type'] = 'lnt_term';
    $term['title'] = $title;
    $term['uid'] = $account->uid; 
    $term['name'] = $account->name;
    $term['status'] = $lnt_image_node->status;                           // propogate status MAYBE HANDLE BY "RELATIONSHIPS" MODULE
    $term['field_lnt_image_element_id'][0]['value'] = $term_id;
    $term['field_lnt_image_noderef'][0]['nid'] = $lnt_image_node->nid;

    // SAVE NODE
    //node_validate($term);
    $term = node_submit($term);
    node_save($term);
}
