<?php

function latnb_init() {
  
  $path = drupal_get_path('module', 'latnb');
  if ($_REQUEST['q'] == 'lat/user/images') {
    drupal_add_js("$path/js/page-add-images-to-notebook.js");
  }
  if (arg(0) == 'notebooks') {
    drupal_add_css("$path/css/notebook-page.css");
    drupal_add_css("$path/css/style.css");
    drupal_add_js("$path/js/notebook-page.js");
  }
  $valid_notebook_ui_paths = array(
    //'lat/user/tags',
    'lat/user/images',
    //'remote-image-search/results'
  );
  if (in_array($_REQUEST['q'], $valid_notebook_ui_paths)) {
    drupal_add_js("$path/js/activity-ui.js");
  }
  
}

function latnb_menu() {
  return array(
    'notebooks' => array(
      'page title' => 'Notebooks',
      'page callback' => '_latnb_page',
      'page arguments' => array(1),
      'menu name' => 'primary-links',
      'access callback' => TRUE,
    ),
    'lat/process/notebook/add/image-nodes' => array(
      'page title' => 'Add notebook item',
      'page callback' => '_latnb_page_item_add',
      'access callback' => TRUE,
    ),
  );
}

function latnb_ctools_plugin_directory($module, $plugin_type) {
  //dpm("$module: plugins/$plugin_type");
  if ($module == 'ctools' && !empty($plugin_type)) {
    return "plugins/$plugin_type";
  }
}

function _latnb_page_item_add() {
  
  $result_string = '';
  $results = array();
  
  // Create "latimage" nodes from "image" nodes.
  $latimages = array();
  if (array_key_exists('images', $_REQUEST)) {
    $images = $_REQUEST['images'];
    $images = explode(':', $images);
    foreach ($images as $image) {
      $latimage = latimage_create('image-nid', $image);
      if ($latimage) {
        $latimages []= $latimage; 
      } 
      else {
        $result_string .= "Node of type 'lnt_image' was not created.\n";
      }       
    } // end foreach
  }
  else {
    $result_string .= "Parameter 'images' missing.\n";
  }

  // Append "latimage" nodes to "notebook.
  if ($latimages) {
    if(array_key_exists('notebook', $_REQUEST)) {
      $notebook = node_load($_REQUEST['notebook']);
      if ($notebook) {
        // Add "latimage" nodes to notebook.
        foreach ($latimages as $latimage) {
          $notebook->field_latimage_ref []= array(
            'nid' => $latimage->nid
          );
          //$result_string .= "Adding image: $latimage->nid.\n";
        }
        node_save($notebook);
        $result_string .= "Notebook '$notebook->title' updated with new images.\n";
      }
      else {
        // Notebook was not loaded.
        $result_string .= "Notebook was not loaded.\n";
      }
    }
    else {
      // Parameter "notebook' missing.
      $result_string .= "Parameter 'notebook' missing.\n";
      
    }
  }
  else {
    // Nodes of type "latimage" were not created.
    $result_string .= "Nodes of type 'lnt_image' were not created.\n";
  }

  // Return results
  header("Content-type: text/plain");
  print json_encode(array('result_string' => $result_string, 'results' => $results));
  module_invoke_all('exit'); 
}

function _latnb_page() {
  $content = '';
  $account_uid = '';
  if (arg(1)) {
    $account_uid = arg(1);
  }
  else {
    $account_uid = $GLOBALS['user']->uid;
  }
  $content .= drupal_get_form('latnb_activityform');
  $content .= views_embed_view('image_notebooks', 'default', $account_uid);
  return $content;
}

function latnb_activityform() {
  return array(
    'notebook_purpose' => array(
      '#type' => 'radios',
      '#title' => t('Create new'),
      '#options' => array(
        'flashcards' => t('Flashcards'),
        'story' => t('Storybook'),
        'album' => t('Picture album'),
        'notebook' => t('Notebook'),
        'worksheet' => t('Worksheet')
      ),
      '#default_value' => 'flashcards',
      '#required' => TRUE,
      '#description' => t('Choose the type of activity to create.'),
    ),
    'title' => array(
      '#type' => 'textfield',
      '#title' => t('Title'),
      '#maxlength' => '128',
      '#required' => TRUE,
      '#description' => t('Enter a title.'),
    ),
    'submit' => array(
      '#type' => 'submit',
      '#value' => 'Create',
    )
  );
}

function latnb_activityform_submit($form, &$form_state) {
  $notebook = _lat_node_initialize('lnt_album');
  $notebook->title = $form_state['values']['title'];
  $notebook->field_activity_type[0]['value'] 
    = $form_state['values']['notebook_purpose']; 
  node_save($notebook);
}

function latnb_addtoactivityform() {
  
  $item_length = 20; 
  $recent_item_count = 200;
  
  // QUERY ACTIVITY CONTAINERS
  $activity_query = <<<EOS
    select 
      n.nid,
      n.title
    from 
      {node} n 
    where 
      n.type = '%s'
      and n.uid = %d
    order by
      n.created desc
EOS;
  $rset = db_query($activity_query, 'lnt_album', $GLOBALS['user']->uid);
  while ($row = db_fetch_object($rset)) {
    $options[$row->nid] 
      = strlen($row->title) < $item_length 
      ? $row->title 
      : substr($row->title, 0, $item_length - 3).'...';
  }

  // CREATE RECENT ACTIVITIES LIST
  $form[''] = array(
    '#type' => 'markup',
    '#value' => t('Then select a notebook to add the images to.'),
  );
  
  // RECENT ACTIVITIES LIST
  $recent_collections = '';
  $recent_collections .= '<div id="recent-notebooks" class="form-item">';
  $recent_collections .= '<label for="recent-notebooks">Recent notebooks:</label>';
  $recent_options = array_slice($options, 0, $recent_item_count, true);
  foreach ($recent_options as $activity_nid => $activity_name) {
    $add_link = l('add', '#', array('attributes' => array(
      'id' => 'activity-nid-'.$activity_nid,
      'data' => $activity_nid,
      'class' => 'add-to-activity-button'
    )));
    $recent_collections .= <<<EOS
      <div><span class="label">$activity_name</span> $add_link</div>
EOS;
  }
  $recent_collections .= '</div>';
  $form['recent_collections_links'] = array(
    '#type' => 'markup',
    '#value' => $recent_collections
  );
  
  // DROP DOWN MENU
  $options = array_slice($options, $recent_item_count, count($options), TRUE);
  if (!empty($options)) {
    $option_keys = array_keys($options);
    $form['activity_list'] = array(
      '#type' => 'select',
      '#multiple' => TRUE,
      '#size' => 8,
      '#title' => t('More notebooks'),
      '#options' => $options,
      '#default_value' => $option_keys[0],
      '#required' => TRUE,
      '#description' => t('Select images, then select a notebook to add the images to.'),
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Add',
    );
  }
  return $form;
}

function latnb_block($op = 'list', $delta = 0, $edit = array()) {
  
  $blocks[0] = array('info' => 'Notebook UI');
  if ($op == 'view' && $delta == 0) {
    $content = '';
    $content .= drupal_get_form('latnb_addtoactivityform');
    return array(
      'subject' => 'Select images',
      'content' => $content 
    );
  }
  
  if ($op == 'list') {
    return $blocks;
  }
  
}
