<?php
/**
 * List of activities for the user to do
 */

function latusernextsteps_init() {
  $path = drupal_get_path('module', 'latusernextsteps');
  drupal_add_css("$path/theme/css/latusernextsteps-user-nextsteps.css", 'module');
}

function latusernextsteps_menu() {
  return array(
    'lat/user/nextsteps' => array(
      'title' => 'Activities',
      'page callback' => 'theme',
      'page arguments' => array('lat_user_nextsteps', 1),
      'access callback' => 'user_is_logged_in',
    ),
  );
}

function latusernextsteps_theme($existing, $type, $theme, $path) {
  return array(
    'lat_user_nextsteps' => array(
      'arguments' => array(),
      'template' => 'lat-user-nextsteps',
      'path' => "$path/theme",
      'file' => 'theme.inc'
    ),
  );
}
