<?php

function lat_imagesources_init() {
  // dpm(services_get_all());  
}

function lat_imagesources_disable() {
  cache_clear_all('services:methods', 'cache');  
}

function lat_imagesources_enable() {
  cache_clear_all('services:methods', 'cache');
}

function lat_imagesources_service() {
  $methods = array(
    array(
      '#method' => 'imagesources.search',
      '#help' => 'Search photo sharing services like Flickr.',
      '#callback' => '_lat_imagesources_search',
      '#access callback' => '_lat_imagesources_access',
      '#return' => 'string',
      '#args' => array(
        array(
          '#name' => 'provider',
          '#type' => 'string',
          '#optional' => false,
          '#description' => 'Options: flickr',
        ),
        array(
          '#name' => 'keywords',
          '#type' => 'string',
          '#optional' => false,
          '#description' => 'Comma-delimited list of keywords.',
        ),
      ), // end args
    ), // end method
  );
  return $methods;
}

function _lat_imagesources_access() {
  return true;
}

function _lat_imagesources_search($provider, $keywords) {
  $results = '';
  switch ($provider) {
    case 'flickr':
    default:
      $results = _lat_imagesources_search_flickr($keywords);
      break;
  }
  return $results;
}

// Search flickr
// Return results
//http://api.flickr.com/services/feeds/photos_public.gne?format=json&tags=cat&tagmode=any
function _lat_imagesources_search_flickr($tags, $format = 'json') {
  $url = url(
    'http://api.flickr.com/services/feeds/photos_public.gne?jsoncallback=?', 
    array( 'query' => array(
      'tags' => urlencode($tags),
      'tagmode' => 'any',
      'format' => $format
    ))
  );
  return lat_curl($url);
}
